name: Terraform

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.9.1

    - name: Initialize Terraform
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve
      #env:
        #AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
        #AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
